Repository py-mine/mcstatus, pull requests merged in 2022-06, with the labels that each got.

#317 Fix typing issue in deprecated decorator
  mcstatus/utils.py
Labels: type: bug, area: API, status: needs review

#333 Don't track pyenv version file
  .gitignore
  .python-version
Labels: status: needs review

#332 Mark project as typed
  mcstatus/py.typed
  pyproject.toml
Labels: type: feature, status: needs review

#334 Add `reset` and `strikethrough` to `STYLE_MAP`
  mcstatus/pinger.py
  mcstatus/tests/test_pinger.py
Labels: type: bug, area: API

#340 Add coveragerc to ignore type-time only lines
  .coveragerc
  .gitignore
Labels: type: feature, status: needs review, area: tests
