Repository py-mine/mcstatus, pull requests merged in 2022-08, with the labels that each got.

#273 Rework connection classes with proper async support
  mcstatus/protocol/connection.py
  mcstatus/tests/test_server.py
Labels: type: bug, type: enhancement, area: API, state: waiting for author

#358 Fix multiple issues in tests
  pyproject.toml
  tests/__init__.py
  tests/protocol/__init__.py
  tests/protocol/test_connection.py
  tests/test_address.py
  tests/test_async_pinger.py
  tests/test_async_querier.py
  tests/test_async_support.py
  tests/test_bedrock_status.py
  tests/test_deprecated_decorator.py
  tests/test_pinger.py
  tests/test_querier.py
  tests/test_retry_decorator.py
  tests/test_server.py
  tests/test_session_id.py
  tests/test_timeout.py
  tox.ini
Labels: area: tests

#379 Ignore socket failure to close during del
  mcstatus/protocol/connection.py
Labels: type: bug, area: API, state: approved

#375 Pep 585
  mcstatus/address.py
  mcstatus/dns.py
  mcstatus/pinger.py
  mcstatus/protocol/connection.py
  mcstatus/querier.py
  mcstatus/utils.py
  poetry.lock
  pyproject.toml
  tests/test_address.py
Labels: type: enhancement, area: API, status: needs review

#383 fix command-line call order for bungeecord servers.
  mcstatus/__main__.py
Labels: type: bug, area: API, state: approved

#384 Show black diff on failures
  .github/workflows/validation.yml
Labels: type: enhancement, status: needs review, area: CI
