Repository py-mine/mcstatus, pull requests merged in 2022-02, with the labels that each got.

#218 Add CODEOWNERS
  .github/CODEOWNERS
Labels: type: feature, status: needs review

#224 Only start workflows on pushes to master
  .github/workflows/tox-test.yml
  .github/workflows/validation.yml
Labels: type: enhancement, status: needs review, area: CI

#221 Cancel workflow if a new one is already running
  .github/workflows/tox-test.yml
  .github/workflows/validation.yml
Labels: type: enhancement, status: needs review, area: CI

#220 Send better workflow embeds on discord
  .github/workflows/status_embed.yml
  .github/workflows/tox-test.yml
  .github/workflows/validation.yml
Labels: type: feature, status: needs review, area: CI

#229 Reset python environment cache for tox-test workflow
  .github/workflows/tox-test.yml
Labels: type: bug, status: needs review, area: CI

#232 Use RdataType enum for dns types
  mcstatus/server.py
  mcstatus/tests/test_server.py
Labels: type: bug, area: API, status: needs review

#228 Don't run pyright on files from .tox environemnt
  pyrightconfig.json
Labels: type: bug, status: needs review

#230 Run command for generating payload with bash
  .github/workflows/tox-test.yml
Labels: type: bug, status: needs review, area: CI

#231 Update README.md
  README.md
Labels: type: enhancement, status: needs review

#234 Update pyright
  poetry.lock
  pyproject.toml
Labels: area: dependencies, state: approved

#235 Create dependabot.yml
  .github/CODEOWNERS
  .github/dependabot.yml
Labels: type: feature, area: dependencies, status: needs review, area: CI

#226 Add precommit
  .github/CODEOWNERS
  .github/workflows/validation.yml
  .pre-commit-config.yaml
  CONTRIBUTING.md
  poetry.lock
  pyproject.toml
  pyrightconfig.json
  tox.ini
Labels: type: feature, area: dependencies, status: needs review, area: CI

#236 Change repo URL
  pyproject.toml
Labels: area: documentation

#242 End CODEOWNERS file with newline
  .github/CODEOWNERS
Labels: type: bug, status: needs review, area: CI
