Repository py-mine/mcstatus, pull requests merged in 2022-09, with the labels that each got.

#391 CRITICAL: Add a temporary fix to fix workflows
  .github/workflows/tox-test.yml
  .github/workflows/validation.yml
Labels: type: bug, status: needs review, area: CI

#387 Use `TypedDict` to avoid all the type casts in status raw response
  mcstatus/pinger.py
  tests/test_pinger.py
Labels: type: enhancement, area: API, state: approved

#394 Remove `flake8-isort`
  .flake8
  poetry.lock
  pyproject.toml
Labels: type: bug, area: dependencies, state: approved

#400 Fix poetry 1.2 support
  .github/workflows/tox-test.yml
  .github/workflows/validation.yml
Labels: type: bug, status: needs review, area: CI
