Repository py-mine/mcstatus, pull requests merged in 2022-03, with the labels that each got.

#251 Use proper types for BedrockStatusResponse
  mcstatus/bedrock_status.py
Labels: type: bug, area: API, status: needs review

#249 Use ISort instead of flake8-import-order
  .github/workflows/validation.yml
  .pre-commit-config.yaml
  mcstatus/tests/protocol/test_connection.py
  mcstatus/tests/test_async_support.py
  poetry.lock
  pyproject.toml
  tox.ini
Labels: type: enhancement, area: dependencies, status: needs review, area: CI

#222 Fix names of the server classes
  mcstatus/__init__.py
  mcstatus/server.py
  mcstatus/tests/test_server.py
  mcstatus/utils.py
Labels: type: enhancement, area: API, status: needs review

#227 Address class
  mcstatus/address.py
  mcstatus/bedrock_status.py
  mcstatus/pinger.py
  mcstatus/protocol/connection.py
  mcstatus/server.py
  mcstatus/tests/protocol/test_connection.py
  mcstatus/tests/test_address.py
  mcstatus/tests/test_async_pinger.py
  mcstatus/tests/test_pinger.py
  mcstatus/tests/test_server.py
  mcstatus/tests/test_timeout.py
Labels: type: feature, area: API, status: needs review

#265 Fix issues with deprecated decorator
  mcstatus/tests/test_deprecated_decorator.py
  mcstatus/utils.py
Labels: type: bug, area: API, status: needs review

#266 Use renamed server classes
  README.md
  mcstatus/scripts/mcstatus.py
Labels: type: bug, area: API, status: needs review

#270 Handle unsorted key-value mappings that can be returned by some query implementations
  mcstatus/querier.py
  mcstatus/tests/test_querier.py
Labels: type: bug, area: API, state: approved

#269 Hodge Podge :stew:
  .pre-commit-config.yaml
  CONTRIBUTING.md
  mcstatus/tests/test_deprecated_decorator.py
  mcstatus/tests/test_server.py
  pyproject.toml
Labels: type: enhancement, area: API, state: approved
