Repository py-mine/mcstatus, pull requests merged in 2022-12, with the labels that each got.

#440 Fix failing CI
  poetry.lock
Labels: type: bug, status: needs review, area: CI, release-blocker

#444 Don't run tests on intermediate versions
  .github/workflows/tox-test.yml
Labels: type: enhancement, status: needs review, area: CI

#443 Add 3.11 to tox.ini
  tox.ini
Labels: type: bug, status: needs review, area: CI

#447 Fix comment in README
  README.md
Labels: type: bug, area: documentation

#439 Fix PMMP Bedrock Servers Query
  mcstatus/bedrock_status.py
Labels: type: bug, state: waiting for author, area: protocol
