Repository py-mine/mcstatus, pull requests merged in 2022-04, with the labels that each got.

#283 Catch NoAnswer exception during lookup
  mcstatus/address.py
  mcstatus/tests/test_address.py
Labels: type: bug, area: API

#285 Ignore .tox directory for flake8
  .flake8
Labels: type: bug, area: API, status: needs review

#284 test: silence some warnings
  mcstatus/tests/test_async_pinger.py
  mcstatus/tests/test_timeout.py
Labels: type: bug, state: approved, area: tests
