Repository py-mine/mcstatus, pull requests merged in 2022-10, with the labels that each got.

#386 Use `|` instead of `typing.Union`, `typing.Optional` (PEP 604)
  mcstatus/address.py
  mcstatus/bedrock_status.py
  mcstatus/dns.py
  mcstatus/pinger.py
  mcstatus/protocol/connection.py
  mcstatus/querier.py
  mcstatus/server.py
  mcstatus/utils.py
  poetry.lock
  pyproject.toml
Labels: type: enhancement, area: API, status: needs review

#393 Add `translation` field to `RawResponseDescriptionWhenDict`
  mcstatus/pinger.py
Labels: type: bug, area: API, state: approved

#401 Use poetry groups
  .github/workflows/tox-test.yml
  poetry.lock
  pyproject.toml
  release.sh
Labels: type: feature, area: dependencies, status: needs review

#416 Bump actions/upload-artifact to v3
  .github/workflows/tox-test.yml
  .github/workflows/validation.yml
Labels: type: enhancement, status: needs review, area: CI

#408 Use `time.perf_counter` for latency
  mcstatus/pinger.py
  mcstatus/server.py
  tests/test_server.py
Labels: type: enhancement, marker: help wanted, state: WIP, area: CI

#421 Bump dependencies in GitHub Actions with dependabot
  .github/dependabot.yml
Labels: type: feature, area: CI

#417 Remove all 3.7 support
  .github/workflows/tox-test.yml
  poetry.lock
  pyproject.toml
  tests/test_address.py
  tests/test_timeout.py
  tox.ini
Labels: type: enhancement, area: dependencies, area: API, state: waiting for author
