Repository py-mine/mcstatus, pull requests merged in 2024-02, with the labels that each got.

#736 Use official `actions/create-github-app-token` for auto-merge
  .github/workflows/dependabot-auto-merge.yml
Labels: area: CI

#578 Implement Forge Data Decoder
  mcstatus/forge_data.py
  mcstatus/querier.py
  mcstatus/status_response.py
  tests/status_response/test_forge_data.py
  tests/status_response/test_java.py
Labels: type: feature, area: API

#743 Make all our dataclasses frozen
  mcstatus/motd/__init__.py
  mcstatus/motd/components.py
  mcstatus/status_response.py
  tests/status_response/test_java.py
Labels: type: enhancement, area: API
