Repository py-mine/mcstatus, pull requests merged in 2025-05, with the labels that each got.

#994 Test status in tests that intended to test status
  tests/test_async_pinger.py
Labels: type: bug, area: tests

#999 Add typing-extensions dep for test uv group
  pyproject.toml
  uv.lock
Labels: type: bug, area: dependencies, status: needs review

#997 Adjust 1.7 notes in docstring to appease linter
  tests/test_cli.py
Labels: area: CI, release-blocker

#998 Add bot as codeowner for .github/ files
  .github/CODEOWNERS
Labels: area: CI

#1000 Fix ruff & revert 997
  tests/test_cli.py
Labels: type: bug, status: needs review, area: CI, release-blocker

#536 Rewrite Query response class to #306's style
  docs/api/basic.rst
  docs/examples/code/player_list_from_query_with_fallback_on_status.py
  mcstatus/querier.py
  mcstatus/responses.py
  tests/responses/test_query.py
  tests/test_async_querier.py
  tests/test_cli.py
  tests/test_querier.py
Labels: area: API, status: stale, type: rewrite

#1007 Fix publish workflow
  .github/workflows/publish.yml
Labels: type: bug, status: needs review, area: CI
